#ifndef TRIANGULAR_MESH_HPP
#define TRIANGULAR_MESH_HPP

#include "config.hpp"
#include "point.hpp"

#include <vector>

class Triangle;



/**
 * Unstructured triangular (2D simplicial) mesh.
 */
class TriangularMesh
{
public:

  TriangularMesh();

  ~TriangularMesh();

  void clear();

  /**
   * Read the existing mesh generated by Gmsh from a .msh file.
   * @param meshfile - a name of the file with the mesh
   */
  void read_msh(const std::string &meshfile);

  Point2 min_coord() const { return _min_coord; }
  Point2 max_coord() const { return _max_coord; }

  int n_elements() const { return _elements.size(); }

  const Triangle& element(int number) const;

  const std::vector<Point2>& get_vertices() const { return _vertices; }

  bool contains_point(const Point2 &point) const;

  int find_element(const Point2 &point,
                   int start_index,
                   bool throw_exception) const;

  int full_search(const Point2 &point) const;

private:

  TriangularMesh(const TriangularMesh&);
  TriangularMesh& operator =(const TriangularMesh &);

  /**
   * Minimal coordinates of the mesh vertices. It may or may not be one of the
   * mesh vertices. It is not especially if the computational domain has
   * curvilinear boundaries. In this case it's a smallest (with respect to
   * coordinates) point of the rectangle surrounding the domain.
   */
  Point2 _min_coord;

  /**
   * Maximal coordinates of the mesh vertices. It may or may not be one of the
   * mesh vertices. It is not especially if the computational domain has
   * curvilinear boundaries. In this case it's a biggest (with respect to
   * coordinates) point of the rectangle surrounding the domain.
   */
  Point2 _max_coord;

  std::vector<Point2> _vertices; ///< Mesh vertices.
  std::vector<Triangle*> _elements; ///< Mesh elements.
  std::vector<std::vector<int> > _node_to_cell; ///< Map between the number of a
                                                ///< node and a list of cells to
                                                ///< which it belongs.

};



#endif // TRIANGULAR_MESH_HPP
